#!/bin/bash
set -e
build_deps=()
for arg in "$@"; do
  build_deps=("$build_deps $(brew deps --include-build -n $arg)");
done

deps=()
for arg in "$@"; do
  deps=("$deps $(brew deps -n $arg)");
done

build_deps="$(echo $build_deps | tr ' ' '\n' | awk '!x[$0]++' | sort)"
deps="$(echo $deps | tr ' ' '\n' | awk '!x[$0]++' | sort)"

if [[ -z $BREW_BUILD_RECURSIVE_DRY_RUN ]]; then
  comm -23 <(echo "$build_deps") <(echo "$deps") | xargs -I{} --no-run-if-empty brew remove {}
else
  comm -23 <(echo "$build_deps") <(echo "$deps") | xargs -I{} --no-run-if-empty echo 'brew remove {}'
fi


