#!/bin/bash
set -e
#set -x
build_deps=()
for arg in "$@"; do
  build_deps=("$build_deps $(brew deps --include-build -n $arg)");
done

build_deps="$(echo $build_deps | tr ' ' '\n' | awk '!x[$0]++' | sort)"

echo "$build_deps"
